blog_home:
    path: /
    defaults: { _controller: AppBundle:Blog:index }
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
